### ISSUE TITLE
Channels can not send via pads

### ISSUE THREAD

**Issue by phlegma** [vvvv/VL.ImGui#28]
If Channels are send via pads a "Object not set to reference" is rised. 

![grafik](https://user-images.githubusercontent.com/358332/180953250-81528772-fde1-4658-8df1-29b24cc6b958.png)

Patch: [PadException-Channels By Path.zip](https://github.com/vvvv/VL.ImGui/files/9187752/PadException-Channels.By.Path.zip)

**Comment by sebescudie** [comment]
Pads are not meant to be used as Send and Receive in the same operation, they would introduce a frame-delay which is I guess why the `Select` node receives a `null`  in your screenshot.

**Comment by gregsn** [comment]
you could however write the Channel into the field on Create
![grafik](https://user-images.githubusercontent.com/575557/186738179-07a1b8d3-273b-49b1-a285-20b5a3961de7.png)
so that link that goes into the pad should be white. then it should work
