### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.ImGui#30]
It looks like:

- Style setters doesn't have Widget input
- Every Widget has Style input
- Style works for the whole trunk of the tree (so Group/Fold/Row/Column also have the Style input, the style is applied to all of the connected widgets)

**Comment by gregsn** [comment]
cc823093fea4e2db11d16e23f41c7ffb5536e6c3

**Comment by antongit** [comment]
Most of the widgets has to be stylable.
The list of the potential candidates, that **doesn't have to** be stylable:

- [ ] IndentUnindent
- [ ] SetItemWidth
- [ ] SetTextWrapPosition
- [ ] Dummy
- [ ] InvisibleButton
- [ ] **SkiaWidget**

**Comment by gregsn** [comment]
b561d9fc563b39ac736460ba114e376dbd31523b 
now defaulting to having a style input
