### ISSUE TITLE
Custom Fonts / Sizes

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.ImGui#52]
@azeno Elias, Joreg and me had a question now:
- is it totally not possible to have dynamic fonts / sizes for imgui, where I can just select fonts on the fly?
- can there be some tool where I can define some (then fixed) fonts / sizes for my project?
- or we can only offer some (like 3?) or (just 1?) fixed fonts and sizes to choose from and that's it?

**Comment by azeno** [comment]
To my understanding it's limited by how many fonts one can pack into the font atlas. Only one font atlas can be used per frame rendered. So we could give the root node some sort of font config input pin where one specifies the desired font(s).

Please also read the official documentation about to get a better understanding about the options & limitations: https://github.com/ocornut/imgui/blob/master/docs/FONTS.md
