### ISSUE TITLE
Add `MenuBar` input to the ToSkiaLayer?

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.ImGui#8]
@azeno: Elias, look, in Order to make a MenuBar for the whole app, not a single window, I had to cons `MenuBar (Main)` in and plug it into the `column` and to the `ToSkiaLayer`. But what if `ToSkiaLayer` will get its own `MenuBar` Input (visible or not)?

![image](https://user-images.githubusercontent.com/1189037/175790760-f9b66d17-c30e-4ecb-b024-fa94b85a4031.png)

**Comment by azeno** [comment]
Sounds good to me to have a separate input for the main menu at the very root. Then we wouldn't need the special version.

**Comment by antongit** [comment]
Hm, maybe then we should get rid of `MenuBar` at all? 
Every window can have a separate `MenuBar` input.

Normal windows will internally call `Begin/EndMenuBar`. And the root will call `Begin/EndMainMenuBar`.

**Comment by azeno** [comment]
Indeed. Will be interesting how the wrapping will look like in immediate mode @gregsn - ah the region has probably two outputs.
